version: '3'
services:
  app:
    image: app:latest
    ports:
      - "8080:8080"
    build:
      dockerfile: Dockerfile
    environment:
      - GITHUB_API_URL=https://api:github:com/
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_API_VERSION=2022-11-28